### ISSUE TITLE
Incorrect Code Snippet in Article

### ISSUE THREAD

**Issue by Lorl0rd** [anshulsanghi-blog/macros-handbook#1]
Hello,

I noticed a small discrepancy between the code snippet in the article and the correct implementation in the repository. The article shows the following code:

```rust
#[proc_macro]
pub fn constant_string(item: TokenStream) -> TokenStream {
    constant_string_impl(args, item)
    //                   ^^^^ 
    //                    -> unnecessary argument
}
```

However, the correct code (as in the [repository](https://github.com/anshulsanghi-blog/macros-handbook/blob/610b43c1f0aa36e87f970a9d774c2689a9439ee9/macros/src/lib.rs#L62)) should be:

```rust
#[proc_macro]
pub fn constant_string(item: TokenStream) -> TokenStream {
    constant_string_impl(item)
}
```

The argument `args` is unnecessary and may cause confusion for readers trying to understand the code. Could you please update the article to reflect the correct implementation?

Thank you very much for the great article and the effort you put into creating it!

**Comment by anshap1719** [comment]
Hi @Lorl0rd Thank you so much for reporting this. I'll get it fixed.

**Comment by anshap1719** [comment]
@Lorl0rd It has been updated. Thanks again for reporting this. I'm closing the issue now.
